[target.riscv32imc-unknown-none-elf]
runner = "probe-rs run --chip esp32c3"

[build]
rustflags = ["-C", "link-arg=-Tlinkall.x"]
target = "riscv32imc-unknown-none-elf"

[alias]
rb = "run --bin"
rrb = "run --release --bin"
bbr = "build --release --bin"
